name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '00 12 * * 1' # Monday 12 PM UTC
concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  LINES: 200
  COLUMNS: 200
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - os: 'windows-latest'
    name: Integration tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup CI
        uses: ./.github/actions/setup-repo
        with:
          python-version: '3.11' # sync with default version in WORKSPACE.
      - name: Install development dependencies and bindings
        run: |
          bazel run pypi_update
          python -m pip install -r requirements/pypi.txt
          ls /opt/hostedtoolcache/Python/
          ls /opt/hostedtoolcache/Python/3.11.8/
          ls /opt/hostedtoolcache/Python/3.11.8/x64/
          ls /opt/hostedtoolcache/Python/3.11.8/x64/include/
          ls /opt/hostedtoolcache/Python/3.11.8/x64/include/python3.11/
          python -m pip install .
      - name: Run tests on python${{ matrix.python-version }}
        run: bazel test tests:ci examples/...
